#include "renderer.hpp"

#include "hid_transport.hpp"

#include <cairo/cairo.h>
#include <fontconfig/fontconfig.h>

#include <algorithm>
#include <cmath>
#include <ctime>
#include <iomanip>
#include <sstream>

namespace cougar {
namespace {

constexpr double pi = 3.14159265358979323846;

void color(cairo_t* cr, double r, double g, double b, double a = 1.0) {
    cairo_set_source_rgba(cr, r, g, b, a);
}

void rounded_rectangle(cairo_t* cr, double x, double y, double width,
                       double height, double radius) {
    const double right = x + width;
    const double bottom = y + height;
    cairo_new_sub_path(cr);
    cairo_arc(cr, right - radius, y + radius, radius, -pi / 2, 0);
    cairo_arc(cr, right - radius, bottom - radius, radius, 0, pi / 2);
    cairo_arc(cr, x + radius, bottom - radius, radius, pi / 2, pi);
    cairo_arc(cr, x + radius, y + radius, radius, pi, 3 * pi / 2);
    cairo_close_path(cr);
}

void fitted_text(cairo_t* cr, const std::string& value, double x, double y,
                 double width, double height, double preferred_size,
                 bool centered, double r, double g, double b,
                 cairo_font_weight_t weight = CAIRO_FONT_WEIGHT_BOLD) {
    cairo_select_font_face(cr, "DejaVu Sans", CAIRO_FONT_SLANT_NORMAL, weight);
    double size = preferred_size;
    cairo_text_extents_t extents{};
    do {
        cairo_set_font_size(cr, size);
        cairo_text_extents(cr, value.c_str(), &extents);
        if (extents.width <= width && extents.height <= height) break;
        size -= 1.0;
    } while (size > 10.0);
    color(cr, r, g, b);
    const double text_x = centered
        ? x + (width - extents.width) / 2.0 - extents.x_bearing
        : x - extents.x_bearing;
    const double text_y = y + (height - extents.height) / 2.0 - extents.y_bearing;
    cairo_move_to(cr, text_x, text_y);
    cairo_show_text(cr, value.c_str());
}

void metric_card(cairo_t* cr, double x, const char* label,
                 unsigned temperature, unsigned load) {
    constexpr double y = 42;
    constexpr double width = 390;
    constexpr double height = 378;
    constexpr double cx_offset = width / 2;
    constexpr double cy = 228;
    constexpr double radius = 137;

    rounded_rectangle(cr, x, y, width, height, 34);
    color(cr, 0.055, 0.067, 0.09, 0.90);
    cairo_fill_preserve(cr);
    color(cr, 0.23, 0.26, 0.32, 0.75);
    cairo_set_line_width(cr, 2);
    cairo_stroke(cr);

    cairo_set_line_cap(cr, CAIRO_LINE_CAP_ROUND);
    cairo_set_line_width(cr, 28);
    color(cr, 0.20, 0.22, 0.27, 1.0);
    cairo_arc(cr, x + cx_offset, cy, radius, -pi / 2, 3 * pi / 2);
    cairo_stroke(cr);
    if (temperature > 0) {
        const double fraction = std::min(temperature, 100u) / 100.0;
        cairo_pattern_t* arc = cairo_pattern_create_linear(x + 40, 0, x + width, 0);
        cairo_pattern_add_color_stop_rgb(arc, 0, 1.0, 0.29, 0.02);
        cairo_pattern_add_color_stop_rgb(arc, 1, 1.0, 0.68, 0.05);
        cairo_set_source(cr, arc);
        cairo_arc(cr, x + cx_offset, cy, radius, -pi / 2,
                  -pi / 2 + 2 * pi * fraction);
        cairo_stroke(cr);
        cairo_pattern_destroy(arc);
    }

    fitted_text(cr, label, x + 40, 82, width - 80, 56, 38, true, 1, 1, 1);
    const std::string temp = temperature
        ? std::to_string(temperature) + " \xC2\xB0" "C"
        : "-- \xC2\xB0" "C";
    fitted_text(cr, temp, x + 35, 173, width - 70, 95, 56, true, 1, 1, 1);
    fitted_text(cr, "LOAD " + std::to_string(load) + "%",
                x + 70, 287, width - 140, 48, 18, true,
                1.0, 0.42, 0.04);
}

} // namespace

bool render_dashboard(const std::string& path, const Metrics& metrics,
                      const std::string& font_file) {
    if (!font_file.empty()) {
        FcConfigAppFontAddFile(nullptr,
            reinterpret_cast<const FcChar8*>(font_file.c_str()));
        FcConfigBuildFonts(nullptr);
    }

    cairo_surface_t* surface = cairo_image_surface_create(
        CAIRO_FORMAT_ARGB32, display_width, display_height);
    if (cairo_surface_status(surface) != CAIRO_STATUS_SUCCESS) {
        cairo_surface_destroy(surface);
        return false;
    }
    cairo_t* cr = cairo_create(surface);
    cairo_set_antialias(cr, CAIRO_ANTIALIAS_BEST);

    cairo_pattern_t* background = cairo_pattern_create_linear(0, 0, display_width, 0);
    cairo_pattern_add_color_stop_rgb(background, 0.0, 0.018, 0.025, 0.045);
    cairo_pattern_add_color_stop_rgb(background, 0.55, 0.035, 0.045, 0.070);
    cairo_pattern_add_color_stop_rgb(background, 1.0, 0.015, 0.020, 0.035);
    cairo_set_source(cr, background);
    cairo_paint(cr);
    cairo_pattern_destroy(background);

    // Asset-free accent lines make the default dashboard recognizable while
    // keeping every rendered pixel generated by this program.
    cairo_pattern_t* accent = cairo_pattern_create_linear(0, 0, 900, 0);
    cairo_pattern_add_color_stop_rgba(accent, 0.0, 1.0, 0.18, 0.02, 0.0);
    cairo_pattern_add_color_stop_rgba(accent, 0.45, 1.0, 0.35, 0.02, 0.85);
    cairo_pattern_add_color_stop_rgba(accent, 1.0, 1.0, 0.58, 0.02, 0.0);
    cairo_set_source(cr, accent);
    cairo_set_line_width(cr, 3);
    cairo_move_to(cr, 42, 64);
    cairo_line_to(cr, 876, 64);
    cairo_stroke(cr);
    cairo_pattern_destroy(accent);

    std::time_t raw_time = std::time(nullptr);
    std::tm now{};
    localtime_r(&raw_time, &now);
    std::ostringstream clock;
    clock << std::put_time(&now, "%H:%M:%S");
    std::ostringstream date;
    date << std::put_time(&now, "%a  %d %b %Y");

    fitted_text(cr, "SYSTEM STATUS", 42, 91, 780, 54, 28, false,
                1.0, 0.40, 0.03);
    fitted_text(cr, clock.str(), 42, 148, 820, 130, 96, false, 1, 1, 1);
    fitted_text(cr, date.str(), 45, 294, 760, 54, 25, false,
                0.66, 0.69, 0.76, CAIRO_FONT_WEIGHT_NORMAL);
    fitted_text(cr, "COUGAR CFV235 LCD", 45, 361, 760, 42, 20, false,
                0.39, 0.42, 0.49, CAIRO_FONT_WEIGHT_NORMAL);

    metric_card(cr, 1010, "CPU", metrics.cpu_temperature, metrics.cpu_load);
    metric_card(cr, 1462, "GPU", metrics.gpu_temperature, metrics.gpu_load);

    cairo_destroy(cr);
    const cairo_status_t status = cairo_surface_write_to_png(surface, path.c_str());
    cairo_surface_destroy(surface);
    return status == CAIRO_STATUS_SUCCESS;
}

} // namespace cougar
